### ISSUE TITLE
问个问题?

### ISSUE THREAD

**Issue by ghost** [AoEiuV020/PaNovel#1]
缓存那一块是怎么实现的呢，有Java代码吗，我先了测试demo，一缓存界面卡顿的不要不要的，也是在多线程模式下的。请指教!请问可以提供demo吗

**Comment by AoEiuV020** [comment]
能卡到界面，那肯定异步没做好啊，缓存写的再糟也不能卡到界面的，
你这话说的都莫名其妙，什么叫“多线程模式”？
总之不要把耗时操作放在ui线程，缓存再怎样都不会卡到界面，
没有java, 没有demo,
