### ISSUE TITLE
新版本广告问题

### ISSUE THREAD

**Issue by Zawinzala** [AoEiuV020/PaNovel#6]
使用了最新版本，广告开幕全屏，时间4s，重启就有没cd，而且没找到任何关闭广告的地方。

建议广告不要全屏显示，时间缩短。

每36小时只显示一次广告。

这也我还能接受。

**Comment by Zawinzala** [comment]
哦，似乎通知也会藏广告进去，我直接关闭通知权限了没在意。好像是伪装成其他app发的广告，发广告也偷偷摸摸。
这次直接4s开屏广告，显然不是第一次添加开发热情了。

**Comment by AoEiuV020** [comment]
通知那个广告我也不知道是怎么回事，极光推送的，但是我没有推，而且后台也没有记录，重置了各种secret也没用，之后考虑删除极光，

**Comment by AoEiuV020** [comment]
@Zawinzala 你说的伪装成其他app发的广告是3.4.0出现的吗？3.4.0更新前我又重置了极光的推送secret、api secret和登录密码，
我自己已经很久没收到这种广告了，按理说不应该再出现了，

**Comment by Zawinzala** [comment]
@AoEiuV020 不知道哪个版本，反正从那以后就没给过通知权限。

**Comment by AoEiuV020** [comment]
开屏广告那个，之后会加上cd，刚上确实草率了，不过不至于36小时什么，要做应该是10分钟或者30分钟这样的，
关闭广告的话其实都到这里了，看看代码也就知道怎么关闭广告了，
